Tutorias/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sysacad/', include('sysacad.urls')),
    path('login/', include('django.contrib.auth.urls')),
    # path('menu/', include('menu.urls')),
    path('select2/', include('django_select2.urls')),
    path('', include('menu.urls')),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

# el name es el nombre al cual debemos referenciar desde los templates o el codigo html.
urlpatterns = [
    path('', views.verNovedades, name = 'index'),
    path('alumno/nuevo', views.agregarAlumno, name = 'alta-alumno'),
    path('alumno/editar/<int:dni>/', views.editarAlumno, name='editar-alumno'),
    path('alumno/buscar', views.buscarAlumno, name = 'buscar-alumno'),
    # path('buscar/alumno/<int:id>', views.buscarAlumnoId, name = 'buscar-alumno-id'),
    path('tutor/nuevo', views.agregarTutor, name = 'alta-tutor'),
    path('tutor/nuevo/alta-personalizada', views.agregarTutorPersonalizado, name = 'alta-tutor-personalizada'),
    path('tutor/buscar', views.buscarTutor, name = 'buscar-tutor'),
    path('tutor/editar/<int:dni>/', views.editarTutor, name='editar-tutor'),
    path('tutor/editar/baja/<int:dni>/', views.bajaTutor, name='baja-tutor'),
    path('tutor/editar/alta/<int:dni>/', views.altaTutor, name='alta-tutor'),
    path('intervencion/nueva', views.agregarIntervencion, name = 'alta-intervencion'),
    path('intervencion/nueva/tipo', views.agregarIntervencionTipo, name = 'alta-tipo-intervencion'),
    path('intervencion/editar/<int:id>/', views.editarIntervencion, name='editar-intervencion'),
    path('intervenciones', views.listarIntervenciones, name = 'intervenciones'),
    path('intervenciones/cerrar/<int:id>/', views.cerrarIntervencion, name = 'cerrar-intervencion'),
    path('intervenciones/abrir/<int:id>/', views.abrirIntervencion, name = 'abrir-intervencion'),
    path('intervenciones/eliminar/<int:id>/', views.eliminarIntervencion, name = 'eliminar-intervencion'),
    path('buscar/alumno/cerrar/<int:id>/', views.cerrarIntervencionB, name = 'cerrar-intervencion-b'),
    path('buscar/alumno/abrir/<int:id>/', views.abrirIntervencionB, name = 'abrir-intervencion-b'),
    path('novedades/panel', views.panelNovedades, name = 'panel-novedades'),
    path('novedades/panel/cerrar/<int:id>/', views.cerrarNovedad, name = 'cerrar-novedad'),
    path('novedades/panel/abrir/<int:id>/', views.abrirNovedad, name = 'abrir-novedad'),
    path('novedades/panel/eliminar/<int:id>/', views.eliminarNovedad, name = 'eliminar-novedad'),
    path('novedad/nueva', views.agregarNovedad, name = 'alta-novedad'),
    path('novedad/editar/<int:id>/', views.editarNovedad, name = 'editar-novedad'),
    path('update_session/<int:collapse>/', views.update_session, name = 'update-session'),
    path('estadisticas', views.estadisticas, name = 'estadisticas'),
    path('password', views.change_password, name='change_password'),
    path('tarea/nueva', views.agregarTarea, name='alta-tarea'),
    path('agenda/<int:year>/<int:month>/<int:day>/', views.bcal, name='agenda-tareas'),
    path('tarea/<int:id>/', views.mostrarTareaId, name='tarea'),
    path('tarea/editar/<int:id>/', views.editarTarea, name='editar-tarea'),
    path('tarea/eliminar/<int:id>/', views.eliminarTarea, name='eliminar-tarea'),
    path('grupo/nuevo', views.agregarGrupo, name = 'alta-grupo'),
    path('grupos', views.listarGrupos, name = 'listar-grupos'),
    path('grupo/editar/<int:id>/', views.editarGrupo, name='editar-grupo'),
    path('grupo/eliminar/<int:id>/', views.eliminarGrupo, name = 'eliminar-grupo'),
    path('informes/ranking-consultas/', views.rankingConsultas, name = 'ranking-consultas'),
    path('informes/estado-escuelas/', views.estadoEscuelas, name = 'estado-escuelas'),
    path('informes/categorizacion-alumnos/', views.categorizacionAlumnos, name = 'categorizacion-alumnos'),
    path('intervencion/tipo/eliminar/<int:id>/', views.eliminarTipoIntervencion, name = 'eliminar-tipo-intervencion'),
    path('materia/nueva', views.agregarMateria, name = 'alta-materia'),
    path('materias', views.listarMaterias, name = 'panel-materias'),
    path('materia/editar/<int:id>/', views.editarMateria, name='editar-materia'),
    path('materia/eliminar/<int:id>/', views.eliminarMateria, name = 'eliminar-materia'),
]

menu/models.py
from django.db import models
from django.utils import timezone
# from compositefk.fields import CompositeForeignKey

class Tipo(models.Model):
    descripcion = models.CharField(max_length=40, unique=True)

    def save(self, *args, **kwargs):
        for campo in ['descripcion']:
            val = getattr(self, campo, False)
            if val:
                val = val.rstrip().replace(',', '').split()
                valor = ''
                for i in val:
                    valor += i.lower().capitalize()+' '
                valor = valor.rstrip()
                setattr(self, campo, valor)
        super(Tipo, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.descripcion)

class Persona(models.Model):
    dni = models.DecimalField(max_digits=12, decimal_places=0, primary_key=True)
    nombre = models.CharField(max_length=60)
    telefono = models.BigIntegerField(blank=True, null=True)
    mail = models.EmailField(max_length=100)
    # carrera = models.CharField(max_length=20, blank=True, null=True)
    # fecha_alta = models.DateTimeField(default=timezone.now)
    # dni = models.OneToOneField('sysacad.Persona', verbose_name='DNI', primary_key=True, on_delete=models.DO_NOTHING)
    # dni = models.ForeignKey('sysacad.Persona', verbose_name='DNI', on_delete=models.DO_NOTHING)
    # legajo = models.IntegerField(unique=True, blank=True, null=True)
    fecha_alta = models.DateTimeField(default=timezone.now)
    fecha_desvinculacion = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

class Tutor(Persona):
    # legajo = models.IntegerField(unique=True, blank=True, null=True)
    legajo = models.IntegerField(blank=True, null=True)
    tipo = models.CharField(max_length=30)
    materia = models.CharField(max_length=100, blank=True, null=True)
    horario = models.CharField(max_length=50, blank=True, null=True)
    usuario = models.CharField(max_length=20, blank=True, null=True)
    # fecha_desvinculacion = models.DateTimeField(null=True, blank=True)

    def estado(self):
        if self.fecha_desvinculacion:
            return 'Inactivo'
        else:
            return 'Activo'

    def save(self, *args, **kwargs):
        for campo in ['nombre', 'materia']:
            val = getattr(self, campo, False)
            if val:
                val = val.rstrip().replace(',', '').split()
                valor = ''
                for i in val:
                    valor += i.lower().capitalize()+' '
                valor = valor.rstrip()
                setattr(self, campo, valor)
        super(Tutor, self).save(*args, **kwargs)

    def __str__(self):
        return 'DNI: {}; Nombre: {}; Tipo: {} --- Estado: {}'.format(self.dni, self.nombre, self.tipo, self.estado())

class Alumno(Persona):
    ciudad_origen = models.CharField(max_length=60, null=True, blank=True)
    ciudad_residencia = models.CharField(max_length=60, null=True, blank=True)
    tipo_escuela = models.CharField(max_length=20, null=True, blank=True, default='No tecnica')
    legajo = models.IntegerField(unique=True)
    situacion_riesgo = models.CharField(max_length=60, null=True, blank=True, default='No')
    tipo_cursado = models.CharField(max_length=60, null=True, blank=True, default='Semipresencial')
    recursante = models.BooleanField(default=False, blank=True)
    motivo_recursante = models.CharField(max_length=60, null=True, blank=True, default=None)
    discapacidad = models.BooleanField(default=False)
    tipo_discapacidad = models.CharField(max_length=40, null=True, blank=True, default=None)
    dejo_seminario = models.BooleanField(default=False, blank=True)
    motivo_dejo_seminario = models.CharField(max_length=60, null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)

    def save(self, *args, **kwargs):
        for campo in ['nombre', 'ciudad_origen', 'ciudad_residencia', 'motivo_recursante', 'motivo_dejo_seminario', 'tipo_discapacidad']:
            val = getattr(self, campo, False)
            if val:
                val = val.rstrip().replace(',', '').split()
                valor = ''
                for i in val:
                    valor += i.lower().capitalize()+' '
                valor = valor.rstrip()
                setattr(self, campo, valor)
        val = getattr(self, 'observaciones', False)
        if val:
            setattr(self, 'observaciones', val.capitalize())
        super(Persona, self).save(*args, **kwargs)

    def __str__(self):
        return ' Legajo: {}, DNI: {}, Nombre: {}'.format(self.legajo, self.dni, self.nombre)

class Intervencion(models.Model):
    alumno = models.ForeignKey('Alumno', on_delete=models.DO_NOTHING)
    # materia = models.ForeignKey('sysacad.Materia', on_delete=models.DO_NOTHING, null=True, blank=True)
    materia = models.IntegerField(null=True, blank=True)
    tutor_asignado = models.ForeignKey('Tutor', on_delete=models.DO_NOTHING)
    tipo = models.ForeignKey('Tipo', on_delete=models.DO_NOTHING)
    medio = models.CharField(max_length=40, default='Personal')
    descripcion = models.TextField(null=True, blank=True)
    estado = models.CharField(max_length=40, default='Abierta')
    fecha_alta = models.DateTimeField(default=timezone.now)
    fecha_baja = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        val = getattr(self, 'descripcion', False)
        # materia = getattr(self, 'materia', False)
        if val:
            setattr(self, 'descripcion', val.capitalize())
        # if materia:
        #     setattr(self, 'materia', materia.materia)
        super(Intervencion, self).save(*args, **kwargs)


    def __str__(self):
        return 'Alumno: {}, Intervencion: {}, {}'.format(self.alumno, self.tipo, self.descripcion)

class Novedades(models.Model):
    titulo = models.CharField(max_length=60, null=True, blank=True)
    descripcion = models.TextField()
    fecha_alta = models.DateTimeField(default=timezone.now)
    estado = models.CharField(max_length=40, default='Activa')

    def save(self, *args, **kwargs):
        for campo in ['titulo']:
            val = getattr(self, campo, False)
            if val:
                val = val.rstrip().replace(',', '').split()
                valor = ''
                for i in val:
                    valor += i.lower().capitalize()+' '
                valor = valor.rstrip()
                setattr(self, campo, valor)
        val = getattr(self, 'descripcion', False)
        if val:
            setattr(self, 'descripcion', val.capitalize())
        super(Novedades, self).save(*args, **kwargs)

class Tarea(models.Model):
    titulo = models.CharField(max_length=25, null=True, blank=True)
    descripcion = models.TextField()
    fecha_alta = models.DateTimeField(default=timezone.now, verbose_name='Fecha programada')
    fecha_baja = models.DateTimeField(null=True, blank=True)
    tutor_asignado = models.ForeignKey('Tutor', on_delete=models.DO_NOTHING)
    estado = models.CharField(max_length=40, default='Abierta')

    def get_absolute_url(self):
        return "/tarea/%d" % self.id

    def save(self, *args, **kwargs):
        for campo in ['titulo']:
            val = getattr(self, campo, False)
            if val:
                val = val.rstrip().replace(',', '').split()
                valor = ''
                for i in val:
                    valor += i.lower().capitalize()+' '
                valor = valor.rstrip()
                setattr(self, campo, valor)
        val = getattr(self, 'descripcion', False)
        if val:
            setattr(self, 'descripcion', val.capitalize())
        super(Tarea, self).save(*args, **kwargs)

class Grupo(models.Model):
    titulo = models.CharField(max_length=60)
    descripcion = models.TextField(null=True, blank=True)
    fecha_alta = models.DateTimeField(default=timezone.now)
    fecha_baja = models.DateTimeField(null=True, blank=True)
    horario = models.CharField(max_length=50, blank=True, null=True)
    alumnos = models.CharField(max_length=200)
    # alumnos = models.ManyToManyField(Alumno)
    tutores = models.ManyToManyField(Tutor)
    estado = models.CharField(max_length=20, null=True, blank=True, default='Abierto')

    def __str__(self):
        return ' Grupo: {}, Horario: {}'.format(self.titulo, self.horario)

    def alumnos_as_list(self):
        return self.alumnos.split(',')

    def save(self, *args, **kwargs):
        for campo in ['titulo']:
            val = getattr(self, campo, False)
            if val:
                valor = val.rstrip().upper()
                setattr(self, campo, valor)
        val = getattr(self, 'descripcion', False)
        if val:
            setattr(self, 'descripcion', val.capitalize())
        super(Grupo, self).save(*args, **kwargs)


class Materia(models.Model):
    materia = models.CharField(max_length=60, unique=True)
    especialidad = models.CharField(max_length=40, unique=True)

    def save(self, *args, **kwargs):
        for campo in ['materia']:
            val = getattr(self, campo, False)
            if val:
                val = val.rstrip().split()
                valor = ''
                for i in val:
                    valor += i.lower().capitalize()+' '
                valor = valor.rstrip()
                setattr(self, campo, valor)
        super(Materia, self).save(*args, **kwargs)

    def __str__(self):
        return '{}, {}'.format(self.materia, self.especialidad)

menu/templates/menu/agenda-tareas.html
{% extends "menu/index.html" %}

{% block title %}<title>Tutorias: Agenda de tareas de tutores</title>{% endblock %}

{% block content %}
    {% if messages %}
        <div class="messages">
            {% for msg in messages %}
                <div class="alert alert-{{msg.level_tag}}" role="alert">{{msg.message}}</div>
                </li>
            {% endfor %}
        </div>
    {% endif %}
    <div style="margin-right: -200px; margin-left: -200px;">
        {{ calendar|safe }}
    </div>

{% endblock %}

menu/templates/menu/alta-tutor.html
{% extends "menu/index.html" %}

{% block title %}<title>Tutorías: Agregar tutor</title>{% endblock %}

{% block content %}

    <script>
        $(function() {
            var tipo = $("#id_tipo");
            var hidden = $("#id_materia");
            hidden.parent().hide();
            if (tipo.val() == 'Academico') {
                    hidden.parent().show();
            } else {
                hidden.parent().hide();
            }
            tipo.change(function() {
                if (tipo.val() == 'Academico') {
                    hidden.parent().show();
                } else {
                    hidden.parent().hide();
                };
            });
        });
    </script>

    {% block warning %}
        {% if not_found %}
            <div id="separador" class="alert alert-danger" role="alert">
                No existe ningún registro en el SYSACAD para el DNI: <b>{{ dni }}</b>. Por favor cargue los datos del tutor manualmente.
            </div>
        {% endif %}
        {% if success %}
            <div id="separador" class="alert alert-success" role="alert">
                El tutor <b>{{ tutor.nombre }}</b> fue agregado correctamente.
            </div>
        {% endif %}
        {% if error_form %}
            <div id="separador" class="alert alert-danger" role="alert">
                Verifique los campos ingresados.
            </div>
        {% endif %}
    {% endblock %}

    {% if alta_manual %}
            <div class="row">
                <div class="col">
                    <h2>Agregar tutor manualmente</h2>
                    <br>
                    <a class="btn btn-secondary" href="{% url 'menu:alta-tutor' %}">Atras</a>
                    <a class="btn btn-primary" href="{% url 'menu:alta-tutor-personalizada' %}">Añadir Manualmente</a>
                </div>
            </div>
    {% else %}
            <div class="alert alert-warning" role="alert">
              Si no es alumno de la facultad, añadir manualmente desde <a href="{% url 'menu:alta-tutor-personalizada' %}" class="alert-link">aquí</a>.
            </div>
            <h2>Nuevo Tutor</h2>
            <div class="row">
                <div class="col">
                    <form method="post">{% csrf_token %}
                        {% include 'common/form_template.html' with form=form %}
                        <button type="submit" style="margin-top: 10px; float: right;" class="btn btn-primary">Añadir</button>
                    </form>
                </div>
            </div>
    {% endif %}

{% endblock %}

menu/templates/menu/buscar-tutor.html
{% extends "menu/index.html" %}

{% block title %}<title>Tutorias: Buscar tutor</title>{% endblock %}

{% block content %}
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        });
    </script>
    {% block warning %}
        {% if not_found %}
            <div class="alert alert-danger" role="alert">
                No existe ningún tutor con el DNI o Legajo ingresado.
            </div>
        {% endif %}
        {% if bad %}
            <div class="alert alert-danger" role="alert">
                El valor ingresado no se corresponde con un DNI o Legajo valido.
            </div>
        {% endif %}
        {% if baja %}
            <div id="separador" class="alert alert-success" role="alert">
                El tutor {{ tutor_inst.nombre }} fue dado de baja el dia de la fecha.
            </div>
        {% endif %}
        {% if alta %}
            <div id="separador" class="alert alert-success" role="alert">
                El tutor {{ tutor_inst.nombre }} fue dado de alta el dia de la fecha.
            </div>
        {% endif %}
    {% endblock %}

    {% if form %}
        <h2>Buscar Tutor</h2>
        <form class="mt-3" method="post">
            {% csrf_token %}
            <div class="form-group">
                {% include 'common/form_busqueda.html' with form=form %}
            </div>
            <div class="clearfix mb-3">
                <div class="float-right">
                    <button type="submit" class="btn btn-secondary"  value="login" tabindex="3">Buscar</button>
                </div>
            </div>
        </form>
    {% endif %}

    {% if tutor %}
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">{% if tutor.fecha_desvinculacion %}Dar de alta tutor{% else %}Dar de baja tutor{% endif %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Está seguro que desea dar de {% if tutor.fecha_desvinculacion %}alta{% else %}baja{% endif %} el tutor <b>{{ tutor.nombre }}</b>?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        {% if tutor.fecha_desvinculacion %}
                            <a class="btn btn-success" href="{% url 'menu:alta-tutor' dni=tutor.dni %}">Dar de alta</a>
                        {% else %}
                            <a class="btn btn-danger" href="{% url 'menu:baja-tutor' dni=tutor.dni %}">Dar de baja</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div id="accordion">
            <div class="card">
                <div class="card-header" id="headingOne" onclick="$.get('{% url "menu:update-session" collapse=1 %}');">
                    <h5 class="mb-0">
                        <button class="btn btn-link btn-block collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseTwo">
                            <h3><span class="pull-left">Datos Personales de {{ tutor.nombre }}</span></h3>
                        </button>
                    </h5>
                </div>
                <div id="collapseOne" class="collapse  {% if request.session.collapse == 1 %}show{% endif %}" aria-labelledby="headingOne" data-parent="#accordion">
                    <div class="card-body" style="margin: -10px -20px -20px -20px;">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><b>Nombre:</b> {{ tutor.nombre }}</li>
                            <li class="list-group-item"><b>DNI:</b> {{ tutor.dni }}</li>
                            <li class="list-group-item"><b>Legajo:</b> {{ tutor.legajo }}</li>
                            <li class="list-group-item"><b>Telefono:</b> {{ tutor.telefono }}</li>
                            <li class="list-group-item"><b>Tipo:</b> {{ tutor.tipo }}</li>
                            {% if tutor.materia %}
                                <li class="list-group-item"><b>Materia/s:</b> {{ tutor.materia }}</li>
                            {% endif %}
                            <li class="list-group-item"><b>Mail:</b> {{ tutor.mail }}</li>
                            <li class="list-group-item"><b>Horario de atención:</b> {{ tutor.horario }}</li>
                            <li class="list-group-item"><b>Fecha de alta:</b> {{ tutor.fecha_alta.date }}</li>
                            {% if tutor.fecha_desvinculacion %}
                                <li class="list-group-item"><b>Fecha de desvinculación:</b> <span class="badge badge-danger">{{ tutor.fecha_desvinculacion }}</span></li>
                            {% endif %}
                        </ul>
                    </div>
                    {% if tutor.fecha_desvinculacion %}
                        <button type="button" class="btn btn-success pull-right mb-3 mr-3" data-toggle="modal" data-target="#exampleModal">Dar de alta</button>
                    {% else %}
                        <button type="button" class="btn btn-danger pull-right mb-3 mr-3" data-toggle="modal" data-target="#exampleModal">Dar de baja</button>
                    {% endif %}
                    <a class="btn btn-primary pull-right mr-2 mb-3" href="{% url 'menu:editar-tutor' dni=tutor.dni %}">Editar</a>
                </div>
            </div>

            <div class="card">
                <div class="card-header" id="headingTwo" onclick="$.get('{% url "menu:update-session" collapse=2 %}');">
                    <h5 class="mb-0">
                        <button class="btn btn-link btn-block collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            <h3><span class="pull-left">Grupos que involucran a {{ tutor.nombre }}</span></h3>
                        </button>
                    </h5>
                </div>
                <div id="collapseTwo" class="collapse  {% if request.session.collapse == 2 %}show{% endif %}" aria-labelledby="headingTwo" data-parent="#accordion">

                    <div class="row mt-4">
                        {% for g in grupos %}
                            <div class="modal fade" id="exampleModalCenter{{ g.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Detalles del grupo: {{ g.titulo }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p><b>Descripción: </b>{{ g.descripcion }}</p>
                                            <p><b>Fecha de creación: </b>{{ g.fecha_alta }}</p>
                                            <p><b>Horario: </b>{{ g.horario }}</p>
                                            <p><b>Tutores encargados: </b></p>
                                            {% for t in g.tutores.all %}
                                                <p class="card-text ml-5">{{ t.nombre }}<br></p>
                                            {% endfor %}
                                            <p><b>Alumnos: </b></p>
                                            {% for a in g.alumnos.all %}
                                                <p class="card-text ml-5">{{ a.nombre }}<br></p>
                                            {% endfor %}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Aceptar</button>
                                            <a class='btn btn-warning' href='{% url 'menu:editar-grupo' id=g.id %}'>Editar grupo</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-4" style="margin-left: 16px; margin-right: -16px;">
                                <div class="card bg-light mb-3" style="max-width: 18rem;">
                                    <div class="card-header"><button type="button" class="btn btn-link" data-toggle='modal' data-target='#exampleModalCenter{{ g.id }}'>
                                        {{ g.titulo }}
                                    </button></div>
                                    <div class="card-body">
                                        <p class="card-text">{{ g.descripcion }}</p>
                                        {% for t in g.tutores.all %}
                                            <p class="card-text"><b>Tutor/es: </b>{{ t.nombre }}<br></p>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            {% if forloop.counter0|add:1|divisibleby:3 %}
                                </div>
                                <div class="row">
                            {% endif %}
                        {% endfor %}

                        </div>
                </div>
            </div>
        </div>

    {% endif %}
    {% if baja or alta %}
        <a class="btn btn-primary pull-right mr-2" href="{% url 'menu:buscar-tutor' %}">Atras</a>
    {% endif %}
{% endblock %}

menu/templates/menu/editar-intervencion.html
{% extends "menu/index.html" %}

{% block title %}<title>Tutorias: Editar alumno</title>{% endblock %}

{% block content %}
    {% block warning %}
        {% if not_found %}
            <div id="separador" class="alert alert-danger" role="alert">
                Error al editar intervención.
            </div>
        {% endif %}
        {% if success %}
            <div id="separador" class="alert alert-success" role="alert">
                La intervención fue editada correctamente.
            </div>
        {% endif %}
    {% endblock %}
    <form method="post">
        {% csrf_token %}
        {% include 'common/form_template.html' with form=form %}
        <button type="submit" style="margin-top: 10px; float: right;" class="btn btn-primary">Aceptar</button>
        <a class="btn btn-secondary pull-right mr-2" style="color: white!important; margin-top: 10px!important;" onClick="javascript:history.go(-1);">Atras</a>
    </form>
{% endblock %}

menu/templates/menu/editar-tutor.html
{% extends "menu/index.html" %}

{% block title %}<title>Tutorias: Editar tutor</title>{% endblock %}

{% block content %}

    <script>
        $(function() {
            var tipo = $("#id_tipo");
            var hidden = $("#id_materia");
            hidden.parent().hide();
            if (tipo.val() == 'Academico') {
                    hidden.parent().show();
                }
            tipo.change(function() {
                if (tipo.val() == 'Academico') {
                    hidden.parent().show();
                } else {
                    hidden.parent().hide();
                };
            });
        });
    </script>

    {% block warning %}
        {% if not_found %}
            <div id="separador" class="alert alert-danger" role="alert">
                No existe ningun tutor con ese legajo o nombre.
            </div>
        {% endif %}
        {% if success %}
            <div id="separador" class="alert alert-success" role="alert">
                El tutor <b>{{ tutor_inst.nombre }}</b> fue editado correctamente.
            </div>
        {% endif %}
        {% if bad_dni %}
            <div id="separador" class="alert alert-danger" role="alert">
                El DNI ingresado es incorrecto, un DNI valido tiene 8 digitos. La edición no fue realizada.
            </div>
        {% endif %}
    {% endblock %}

    <h2>Editar Tutor</h2>
    <form method="post">
        {% csrf_token %}
        {% include 'common/form_template.html' with form=form %}
        <button type="submit" style="margin-top: 10px; float: right;" class="btn btn-primary">Aceptar</button>
        <a class="btn btn-secondary pull-right mr-2" style="margin-top: 10px!important;" href="{% url 'menu:buscar-tutor' %}">Atras</a>
    </form>

{% endblock %}